basic/models/Books.php
<?php

namespace app\models;

use Yii;
use \yii\db\CDbExpression;

/**
 * This is the model class for table "books".
 *
 * @property integer $id
 * @property string $name
 * @property string $date_create
 * @property string $date_update
 * @property string $preview
 * @property string $date
 * @property integer $author_id
 *
 * @property Authors $author
 */
class Books extends \yii\db\ActiveRecord
{
    private $oldPreview;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'books';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'date_create', 'date_update', 'author_id'], 'required'],
            [['preview'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, gif'],
            [['date_create', 'date_update', 'date'], 'safe'],
            [['author_id'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios['save'] = ['name','date_create', 'date_update', 'preview', 'date', 'author_id'];//Scenario Values Only Accepted
        return $scenarios;
    }

    public function upload()
    {
        $path = 'uploads/' . uniqid() . '.' . $this->preview->extension;
        $uploaded = $this->preview->saveAs($path);
        if ($uploaded){
            $this->preview = $path;
            return true;
        }else{
            return false;
        }
        
    }

    public function afterFind(){
        $this->oldPreview = $this->preview;
    }

    public function beforeValidate(){
        if ($this->scenario == "save"){
            if ($this->isNewRecord)
                $this->date_create = date("Y-m-d H:i:s");
            $this->date_update = date("Y-m-d H:i:s");
        }
        $this->date = date("Y-m-d", strtotime($this->date));
        return parent::beforeValidate();
        
    }

    public function beforeSave($insert){        
        if (parent::beforeSave($insert)){
            if (!empty($this->preview)){
                if ($this->upload()){
                    return true;
                }else{
                    $this->errors['preview'] = "Не удаётся сохранить файл";
                    return false;
                }
            }else{
                $this->preview = $this->oldPreview;
                return true;
            }

        }
        
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Название'),
            'date_create' => Yii::t('app', 'Дата создания'),
            'date_update' => Yii::t('app', 'Дата изменения'),
            'tpreview' => Yii::t('app', 'Картинка'),
            'preview' => Yii::t('app', 'Картинка'),
            'date' => Yii::t('app', 'Дата выхода книги'),
            'author_id' => Yii::t('app', 'Автор'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Authors::className(), ['id' => 'author_id']);
    }

}

basic/controllers/BooksController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Books;
use app\models\BooksSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\Url;

/**
 * BooksController implements the CRUD actions for Books model.
 */
class BooksController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Books models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BooksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        Url::remember(); 

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Books model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id, $mode="")
    {
        $model = $this->findModel($id);
        if ($mode == "ajax"){
            return $this->renderPartial('view', [
                'model' => $model,
            ]);
        }else{
            return $this->render('view', [
                'model' => $model,
            ]);
        }

    }

    /**
     * Creates a new Books model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Books(['scenario' => 'save']);
        $model->scenario = "save";
        if ($model->load(Yii::$app->request->post())) {
            
            $model->preview = UploadedFile::getInstance($model, 'preview');
            if ($model->save()){
                return $this->redirect(['index']);
            }
        } 
        return $this->render('create', [
            'model' => $model,
        ]);
        
    }

    /**
     * Updates an existing Books model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @param string $mode
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->scenario = "save";

        if ($model->load(Yii::$app->request->post())) {
            
            $model->preview = UploadedFile::getInstance($model, 'preview');
            if ($model->save()){
                if (Url::previous()){
                    return Yii::$app->getResponse()->redirect(Url::previous());
                }else{
                    return $this->redirect(['index']);
                }
            }
        } 
         return $this->render('create', [
            'model' => $model,
        ]);
       
    }

    /**
     * Deletes an existing Books model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Books model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Books the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Books::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

basic/views/books/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Authors;
use \yii\jui\yii\base\Model;

/* @var $this yii\web\View */
/* @var $model app\models\Books */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="books-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->errorSummary($model); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'preview')->fileInput() ?>

    <?= $form->field($model, 'date')->textInput(['class'=>'datepicker form-control']) ?>
    <?// ->widget(\yii\jui\DatePicker::classname(), [
    //     //'language' => 'ru',
    //     //'dateFormat' => 'yyyy-MM-dd',
    // ]) ?>

    <?=  $form->field($model, 'author_id')
        ->dropDownList(
            Authors::getFormatedList(),
            ['prompt'=>'']    // options
        );?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Добавить') : Yii::t('app', 'Изменить'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/books/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
// use yii\jui\DatePicker;
use app\models\Authors;

/* @var $this yii\web\View */
/* @var $model app\models\BooksSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="books-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <div class="row">
        <div class="col-xs-4">
            <?
                echo $form->field($model, 'author_id')
                ->dropDownList(
                    Authors::getFormatedList(),
                    ['prompt'=>'']    // options
                );
            ?>
        </div>
        <div class="col-xs-4">
            <?= $form->field($model, 'name') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-8">
            Дата выхода книги: <?= $form->field($model, 'dateFrom', ['template' => "{input}"])->textInput(['class'=>'datepicker form-control'])->label("")?>
            по <?= $form->field($model, 'dateTo', ['template' => "{input}"])->textInput(['class'=>'datepicker form-control'])->label("")?>

            <?// ->widget(DatePicker::classname(), [
            //     'language' => 'ru',
            //     'dateFormat' => 'yyyy-MM-dd',
            // ]) ?>
        </div>
    </div>

    <?php // echo $form->field($model, 'date') ?>

    <?php // echo $form->field($model, 'author_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Искать'), ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/books/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Books */

$this->title = Yii::t('app', 'Добавить книгу');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Книги'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="books-create">
	
	

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

basic/views/books/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $searchModel app\models\BooksSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Книги');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="books-index">
<?php //phpinfo() ?>
    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= $this->render('_search', [
        'model' => $searchModel,
    ]) ?>

    <p>
        <?= Html::a(Yii::t('app', 'Добавить книгу'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'filterPosition' => "",
        'columns' => [
            [
                'attribute' => 'id',
                'contentOptions' => ['width'=>30] // ужимаем колонку
            ],
            'name',
            [
                'attribute' => 'preview',
                'format' => 'html',
                'value' => function($model, $key, $index, $column){
                    return \yii\helpers\Html::a(\yii\helpers\Html::img($model->preview, ["width"=>100]), $model->preview, ["class"=>"fancybox"]);
                }, 
                'contentOptions' => ['width' => 100]
            ],
            [
                'attribute' => 'author_id',
                'value' => 'author.formatedName'
            ],
            // 'author.formatedName',
            [
                'attribute' => 'date',
                'value' => function($model, $key, $index, $column){
                    return Yii::$app->formatter->asDatetime($model->date, "php:d.m.Y");
                }, 
            ],
            [
                'attribute' => 'date_create',
                'value' => function($model, $key, $index, $column){
                    return Yii::$app->formatter->asDatetime($model->date_create, "php:d.m.Y H:i:s");
                }, 
            ],  
            // 'date_update',

            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Кнопки действий',
                'buttons'=>[
                    'view'=>
                        function ($url, $model) {
                            $customurl=Yii::$app->getUrlManager()->createUrl(['books/view','id'=>$model->id, 'mode'=>'ajax']); //$model->id для AR
                            return \yii\helpers\Html::a( 
                                '<span class="glyphicon glyphicon-eye-open"></span>', 
                                $customurl,
                                [
                                    'title' => Yii::t('yii', 'View'), 
                                    'onclick'=>"
                                         $.ajax({
                                            type     :'GET',
                                            cache    : false,
                                            url  :  $(this).attr('href'),
                                            success  : function(response) {
                                                $('#viewModal').find('.modal-body').html(response).end().modal('show');
                                            }
                                        });
                                    return false;",
                                ]);
                        }
                ],
                'contentOptions' => ['align'=>'center']
            ],
        ],
    ]); ?>

</div>

<?
Modal::begin([
    'header' => '<h2>Просмотр книги</h2>',
    'id' => 'viewModal',
]);
Modal::end();
?>

basic/views/books/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Books */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Books',
]) . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Books'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="books-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

basic/views/books/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Books */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Books'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="books-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p class="text-center"><?=Html::img($model->preview, ['height'=>300, 'alt'=>$this->title]);?></p>
     <blockquote>
      <p><?=$model->author->formatedName?>, <?=Yii::$app->formatter->asDatetime($model->date, "php:d.m.Y")?></p>
    </blockquote>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'date_create',
            'date_update',
        ],
    ]) ?>

</div>